-- Клиенты (заёмщики) NBCO

create table clients (
    id          bigint generated by default as identity primary key,
    created_at  timestamptz not null,
    updated_at  timestamptz not null,
    tenant_id   bigint not null,
    pin         varchar(32) not null,
    first_name  varchar(128),
    last_name   varchar(128),
    middle_name varchar(128),
    birth_date  date,
    gender      varchar(16),
    phone       varchar(32),
    address     varchar(512),
    secret_word varchar(128),
    created_by  bigint,
    modified_by bigint,
    constraint uq_client_pin unique (tenant_id, pin)
);
create index ix_client_phone on clients(phone);
create index ix_client_last_name on clients(last_name);
create index ix_clients_tenant on clients(tenant_id);
