-- Файлы загрузки кредитов

create table credit_files (
    id            bigint generated by default as identity primary key,
    created_at    timestamptz not null,
    updated_at    timestamptz not null,
    tenant_id     bigint not null,
    file_name     varchar(256) not null,
    uploaded_by   bigint,
    total_rows    int not null default 0,
    imported_rows int not null default 0,
    failed_rows   int not null default 0,
    status        varchar(16) not null,
    errors        varchar(2000)
);
create index ix_credit_files_tenant on credit_files(tenant_id);
